# Generated by Django 4.1 on 2024-09-08 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="daily_dee",
            new_name="daily_fee",
        ),
    ]
