# Generated by Django 4.1 on 2024-09-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="borrower",
            new_name="user",
        ),
    ]
