# Generated by Django 4.1 on 2024-09-15 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("borrowings", "0005_alter_borrowing_book_alter_borrowing_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="borrowing",
            old_name="book",
            new_name="borrowed_book",
        ),
        migrations.RenameField(
            model_name="borrowing",
            old_name="user",
            new_name="borrower",
        ),
    ]
